resource "time_sleep" "wait_5_seconds" {
  destroy_duration = "5s"
}

resource "google_pubsub_topic" "my_topic" {
  depends_on = [time_sleep.wait_5_seconds]
  project    = var.project
  name       = local.topic
  labels     = local.labels
}
resource "google_pubsub_subscription" "my_subscription" {
  project = var.project
  name    = local.subscription
  topic   = google_pubsub_topic.my_topic.name
  labels  = local.labels
}

# required when reading from PubSubOI without timestamp attribute
#resource "google_pubsub_subscription_iam_member" "grant_sa_editor_role_to_subscription" {
#  project      = var.project
#  subscription = google_pubsub_subscription.my_subscription.name
#  role         = "roles/pubsub.editor" # required to read from subscription (without timestamp attribute)
#  member       = "serviceAccount:${var.service_account}"
#}

# custom fine-grained approach recommended by google, cannot be applied due to permissions issue in project

# resource "google_pubsub_topic_iam_member" "grant_sa_subscriber_role_to_topic" {
#   project = var.project
#   topic   = google_pubsub_topic.my_topic.name
#   role    = "roles/pubsub.subscriber" // contains pubsub.topics.attachSubscription permission
#   member  = "serviceAccount:${var.service_account}"
# }

# creating the custom project role projects/project/roles/pubsubSubscriptionManagerForDataflow: googleapi: Error 403: You don't have permission to create a role in projects/project., forbidden
# custom role with minimal permissions for PubSubIO to create/delete watermark tracking subscriptions
# resource "google_project_iam_custom_role" "pubsub_subscription_manager_for_dataflow" {
#   project     = var.project
#   role_id     = "pubsubSubscriptionManagerForDataflow"
#   title       = "Pub/Sub Subscription Manager For Dataflow"
#   permissions = [
#     "pubsub.subscriptions.create",
#     "pubsub.subscriptions.consume",
#     "pubsub.subscriptions.delete",
#   ]
# }

# Required when reading from PubSubIO with timestampAttribute to create a watermark tracking subscription with autogenerated name.
# resource "google_project_iam_member" "grant_sa_pubsub_custom_role_for_dataflow_at_project" {
#   project = var.project
#   role    = google_project_iam_custom_role.pubsub_subscription_manager_for_dataflow.id
#   member  = "serviceAccount:${var.service_account}"
# }


# required when reading from PubSubIO with timestampAttribute creating a watermark tracking subscription with autogenerated name.
# fixed Internal Issue. Causes: Deleting watermark tracking pubsub subscription projects/project/subscriptions/bartek-topic-sub__df_internalc8b... failed with error: User not authorized to perform this action.
resource "google_project_iam_member" "grant_sa_pubsub_editor_role_at_project" {
  project = var.project
  role    = "roles/pubsub.editor"
  member  = "serviceAccount:${var.service_account}"
}
