resource "time_sleep" "wait_5_seconds" {
  destroy_duration = "5s"
}

resource "google_pubsub_topic" "my_topic" {
  depends_on = [time_sleep.wait_5_seconds]
  project    = var.project
  name       = local.topic
  labels     = local.labels
}
resource "google_pubsub_subscription" "my_subscription" {
  project = var.project
  name    = local.subscription
  topic   = google_pubsub_topic.my_topic.name
  labels  = local.labels
}

# required when reading from PubSubOI without timestamp attribute
#resource "google_pubsub_subscription_iam_member" "grant_sa_editor_role_to_subscription" {
#  project      = var.project
#  subscription = google_pubsub_subscription.my_subscription.name
#  role         = "roles/pubsub.editor" # required to read from subscription (without timestamp attribute)
#  member       = "serviceAccount:${var.service_account}"
#}

# required when reading from PubSubIO with timestampAttribute creating a watermark tracking subscription with autogenerated name.
resource "google_project_iam_member" "grant_sa_editor_role_at_project" {
  project = var.project
  role    = "roles/pubsub.editor"
  member  = "serviceAccount:${var.service_account}"
}
