#!/usr/bin/env bash

# Code generated by AI GPT-5.3-Codex High

set -euo pipefail

# Post-destroy cleanup for Dataflow classic template jobs with the same name.
# It discovers active same-name jobs (optionally excluding the Terraform-tracked job),
# drains them first, and cancels any that do not reach terminal state within timeouts.
# Timeout behavior: poll every 10s, wait up to 300s for drain completion,
# then wait up to 300s for cancel completion if fallback cancellation is needed.
# Safety note: this intentionally drains/cancels all active jobs with this name,
# which is not always desired in production-like environments; here it is for testing only.

PROJECT=""
REGION=""
JOB_NAME=""
TRACKED_JOB_ID=""

log() {
  echo "[$(date '+%Y-%m-%dT%H:%M:%S%z')] $*"
}

usage() {
  cat <<'EOF'
Usage:
  dataflow-cleanup-destroy.sh \
    --project <project-id> \
    --region <region> \
    --job-name <dataflow-job-name> \
    [--tracked-job-id <terraform-tracked-job-id>]
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      PROJECT="${2:-}"
      shift 2
      ;;
    --region)
      REGION="${2:-}"
      shift 2
      ;;
    --job-name)
      JOB_NAME="${2:-}"
      shift 2
      ;;
    --tracked-job-id)
      TRACKED_JOB_ID="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 2
      ;;
  esac
done

if [[ -z "$PROJECT" || -z "$REGION" || -z "$JOB_NAME" ]]; then
  log "Missing required arguments."
  usage
  exit 2
fi

log "Starting Dataflow destroy cleanup script with parameters:"
log "  project=$PROJECT, region=$REGION, job_name=$JOB_NAME"
if [[ -n "$TRACKED_JOB_ID" ]]; then
  log "  tracked_job_id=$TRACKED_JOB_ID"
else
  log "  tracked_job_id=<not provided>"
fi

if ! command -v gcloud >/dev/null 2>&1; then
  log "gcloud is not available; skipping post-destroy Dataflow check for ${JOB_NAME}."
  exit 0
fi

wait_for_terminal_jobs() {
  local action_label="$1"
  local max_wait_seconds="$2"
  local current_job_ids="$3"
  local sleep_seconds=10
  local elapsed_seconds=0
  local job_id=""
  local job_state=""

  WAIT_REMAINING_JOB_IDS="$current_job_ids"
  WAIT_PENDING_STATUSES=""

  while [[ "$elapsed_seconds" -lt "$max_wait_seconds" ]]; do
    WAIT_REMAINING_JOB_IDS=""
    WAIT_PENDING_STATUSES=""

    for job_id in $current_job_ids; do
      job_state="$(gcloud dataflow jobs describe "$job_id" \
        --project="$PROJECT" \
        --region="$REGION" \
        --format="value(currentState)" 2>/dev/null || true)"

      case "$job_state" in
        JOB_STATE_DRAINED|JOB_STATE_DONE|JOB_STATE_CANCELLED|JOB_STATE_FAILED|JOB_STATE_UPDATED)
          ;;
        "")
          ;;
        *)
          WAIT_REMAINING_JOB_IDS="$WAIT_REMAINING_JOB_IDS $job_id"
          WAIT_PENDING_STATUSES="$WAIT_PENDING_STATUSES $job_id:$job_state"
          ;;
      esac
    done

    if [[ -z "$WAIT_REMAINING_JOB_IDS" ]]; then
      log "All remnant Dataflow jobs reached terminal states within $elapsed_seconds seconds (${action_label})."
      return 0
    fi

    current_job_ids="$WAIT_REMAINING_JOB_IDS"
    log "Waiting for remnant jobs to ${action_label}. Pending:${WAIT_PENDING_STATUSES}"
    sleep "$sleep_seconds"
    elapsed_seconds=$((elapsed_seconds + sleep_seconds))
  done

  log "Timed out after $max_wait_seconds seconds waiting for remnant jobs to ${action_label}. Last pending states:${WAIT_PENDING_STATUSES}"
  return 1
}

ACTIVE_JOB_IDS="$(gcloud dataflow jobs list \
  --project="$PROJECT" \
  --region="$REGION" \
  --status=active \
  --filter="name=$JOB_NAME" \
  --format="value(id)" || true)"

if [[ -n "$TRACKED_JOB_ID" ]]; then
  REMNANT_JOB_IDS="$(printf '%s\n' "$ACTIVE_JOB_IDS" | sed '/^$/d' | grep -v "^$TRACKED_JOB_ID$" || true)"
  log "Filtering out tracked job id '${TRACKED_JOB_ID}' from active same-name jobs."
else
  REMNANT_JOB_IDS="$(printf '%s\n' "$ACTIVE_JOB_IDS" | sed '/^$/d' || true)"
  log "No tracked job id provided; all active same-name jobs are candidates for cleanup."
fi

if [[ -n "$ACTIVE_JOB_IDS" ]]; then
  log "Active same-name job IDs discovered:"
  printf '%s\n' "$ACTIVE_JOB_IDS"
else
  log "No active same-name jobs returned by gcloud jobs list."
fi

if [[ -z "$REMNANT_JOB_IDS" ]]; then
  log "No remnant job IDs to process."
  exit 0
fi

log "Remnant job IDs selected for drain:"
printf '%s\n' "$REMNANT_JOB_IDS"

log "Starting drain for remnant job ids..."
for job_id in $REMNANT_JOB_IDS; do
  log "Draining Dataflow job '$job_id'..."
  gcloud dataflow jobs drain "$job_id" \
    --project="$PROJECT" \
    --region="$REGION" || true
done

if ! wait_for_terminal_jobs "drain" 300 "$REMNANT_JOB_IDS"; then
  log "Drain wait timed out. Remaining job IDs selected for cancel:"
  printf '%s\n' "$WAIT_REMAINING_JOB_IDS"

  for job_id in $WAIT_REMAINING_JOB_IDS; do
    log "Cancelling Dataflow job '$job_id'..."
    gcloud dataflow jobs cancel "$job_id" \
      --project="$PROJECT" \
      --region="$REGION" || true
  done

  wait_for_terminal_jobs "cancel" 300 "$WAIT_REMAINING_JOB_IDS" || true
fi
